### ISSUE TITLE
Can you please provide the pseudocode?

### ISSUE THREAD

**Issue by shuangyichen** [1hunters/LIMPQ#1]
Hey, your work is so well-presented! Can you please provide the supplementary material and the pseudocode?  I would be much appreciated if you could.

**Comment by 1hunters** [comment]
Hi shuangyi,

You can find the supplementary material and the pseudocode for the importance indicator training at [this link](https://www.ecva.net/papers/eccv_2022/papers_ECCV/papers/136710260-supp.pdf).

**Comment by shuangyichen** [comment]
> Hi shuangyi,
> 
> You can find the supplementary material and the pseudocode for the importance indicator training at [this link](https://www.ecva.net/papers/eccv_2022/papers_ECCV/papers/136710260-supp.pdf).

Thanks so much!
