### ISSUE TITLE
Error help

### ISSUE THREAD

**Issue by ganjuzhizihuai** [1hunters/LIMPQ#4]
Hello, I would like to ask you a question. I encountered a problem when I was copying the code. In the line of code model = timm.create_model('resnet50.gluon_in1k', pretrained=args.pre_trained), the error showed that urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f3dc8140460>: Failed to establish a new connection: [Errno 101] Network is unreachable。 I am using a domestic server. I would like to ask how you run the download and what platform environment is it under?
I will be very grateful for your answer.

**Comment by 1hunters** [comment]
This is a networking issue of your server. Please make sure your server is accessible to Huggingface for downloading the pretrained models, or you can change the source of the pretrained model to Torchvision.

**Comment by ganjuzhizihuai** [comment]
> This is a networking issue of your server. Please make sure your server is accessible to Huggingface for downloading the pretrained models, or you can change the source of the pretrained model to Torchvision.

Thank you very much. I change the source of the pretrained model to Torchvision and the problem has been solved.
