### ISSUE TITLE
Search ERROR

### ISSUE THREAD

**Issue by ganjuzhizihuai** [1hunters/LIMPQ#5]
Hello, when I searched for the bit width of ResNet18, I got an error:    
cons = lpSum([bit_ops[i] * avg_bit_w *
IndexError: list index out of range. 
Then I printed it and got the following output information: 
layer_wise_act: 21
layer_wise_weight: 21
layer_name_list: 21
model_name: resnet18
Length of bit_ops: 19
Why does inequality occur? This did not happen when I ran ResNet50.

**Comment by 1hunters** [comment]
Maybe you should not include the first layer and last layer in the indicator file because they are not quantized with mixed precision (as stated in our paper). BTW, if the previous issue was addressed properly, please consider closing it.
